spring:
  application:
    name: fastfood
  datasource:
    url: jdbc:postgresql://db:5432/fastfood
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update